### PR TITLE
Removing working groups + leadership

### PR DESCRIPTION
**Pull request by cjosu**
Can re-introduce leadership pending an updated list of personnel

### CODE REVIEW

**Review by ahwagner — CHANGES_REQUESTED** [review]
I did not mean to have the leadership tab removed in its entirety; we should still have leadership, just change up [the leadership page](https://github.com/cancervariants/cancervariants.org/blob/master/pages/leadership.md) to remove the _Working Group_ leadership.

Also, while this will remove navigation to those pages, I would like [the pages themselves](https://github.com/cancervariants/cancervariants.org/tree/master/pages/working_groups) to also be removed and any incoming traffic to those pages to redirect to the VICC home page.

EDIT: we should preserve the KCIS page for now; the other pages may be removed / redirected to the home page.

**Comment by cjosu** [comment]
> EDIT: we should preserve the KCIS page for now; the other pages may be removed / redirected to the home page.

Re-introduced Working Groups to show KCIS (which is now the only Working Group). Can handle this differently if need be.

**Comment by ahwagner** [comment]
This is a tricky situation–one of the WG leads has been continuing to promote the KCIS working group as the source of activities for the project despite the consortium transition away from working groups. There seems to be some miscommunication going on.

I will be discussing with the other VICC directors about how we want to handle this collectively. In the meantime, we should still hide the working group navbar even if we allow direct-link landing on the KCIS page.

**Comment by cjosu** [comment]
Commented out for now. Still looking into autobuilding PRs for Jekyll.

**Review by ahwagner — APPROVED** [review]

**Comment by ahwagner** [comment]
Great. Let's open that feature as a separate issue.

**Pull request merged**
